"""empty message

Revision ID: ab8a25125e40
Revises: 6f2dcc94adc0
Create Date: 2020-04-24 13:59:37.979774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8a25125e40'
down_revision = '6f2dcc94adc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('allowences', sa.Integer(), nullable=True))
    op.drop_column('entries', 'allocations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('allocations', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'allowences')
    # ### end Alembic commands ###
