"""empty message

Revision ID: f61cb8ab2a57
Revises: ab8a25125e40
Create Date: 2020-04-24 16:28:36.118372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61cb8ab2a57'
down_revision = 'ab8a25125e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'allowences',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entries', 'deductions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entries', 'hours_worked',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'hours_worked',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entries', 'deductions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entries', 'allowences',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
